add-system-status-page
freifunk-berlin/firmware-wizard-frontend pull request #94
Opened 2017-07-09 20:35 UTC by andibraeu

2017-07-10 07:05 UTC, andrenarchy requested changes

2017-07-10 07:05 UTC, andrenarchy commented on src/components/status-system/status-system.less
> +}
We should wrap the less definitions so we don't pollute the global space
```less
status-system {
  dt {
    //...
  }
  // ...
}

2017-07-10 07:05 UTC, andrenarchy commented on src/filters/byte-format.js
> +      if (bytes === 0) return '0 MB';
let's move this to the top and add a `if (bytes === undefined) return undefined;` (this may happen when the data is not yet ready for a template)

2017-07-10 07:05 UTC, andrenarchy commented on src/nls/locale-en.json
> +      "noLinks": "Currentl,y there are no links.",
this looks like a typo ;)

2017-07-11 10:19 UTC, andrenarchy approved these changes

2017-07-12 21:01 UTC, andrenarchy commented on src/filters/byte-format.js
> +      if (isNaN(parseFloat(bytes)) || !isFinite(bytes)) return '-';
why do we need `parseFloat` here?

2017-07-16 19:29 UTC, merged

2017-07-16 19:30 UTC, andibraeu commented on src/filters/byte-format.js
> +      if (isNaN(parseFloat(bytes)) || !isFinite(bytes)) return '-';
We use bytes as float later, so it isn't the worst idea to check if we can parse this as float

2017-07-17 09:18 UTC, andrenarchy commented on src/filters/byte-format.js
> +      if (isNaN(parseFloat(bytes)) || !isFinite(bytes)) return '-';
Wait, `bytes` already is a `Number`, right? Then there's no need to parse it again...

2017-07-17 10:32 UTC, andibraeu commented on src/filters/byte-format.js
> +      if (isNaN(parseFloat(bytes)) || !isFinite(bytes)) return '-';
At the moment rpcd returns a number for that. Do we trust that?

2017-07-17 10:44 UTC, andrenarchy commented on src/filters/byte-format.js
> +      if (isNaN(parseFloat(bytes)) || !isFinite(bytes)) return '-';
Never trust a junkie.

2017-07-17 10:46 UTC, andrenarchy commented on src/filters/byte-format.js
> +      if (isNaN(parseFloat(bytes)) || !isFinite(bytes)) return '-';
Seriously, the rest wouldn't work if it's not a number. Anyway, the `parseFloat` doesn't hurt since it's idempotent.